--- #YAML:1.0
name:                RT-Client-REST
version:             0.31
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Error:                         0
    Exception::Class:              0
    HTTP::Cookies:                 0
    HTTP::Request::Common:         0
    LWP:                           0
    Params::Validate:              0
    Test::Exception:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
